name: hive_repository
description: A DatabaseAdapter for the hive database as used by the database_repository package
version: 0.1.0
repository: https://github.com/glassp/hive_repository

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  database_repository: ^1.1.0
  hive: ^2.0.5
  meta: ^1.7.0
  uuid: ^3.0.5
dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.20.1
