name: hive_repository
description: A DatabaseAdapter for the hive database as used by the database_repository package
version: 0.1.0
repository: https://github.com/glassp/hive_repository

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  meta: ^1.7.0
dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.20.1
