name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, beta, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Install global dependencies
        run: dart pub global activate coverage

      - name: Check Code Formating
        run: dart format . -o none --set-exit-if-changed

      - name: Check Code Quality
        run: dart analyze --fatal-infos

      - name: Running Tests
        run: dart test --coverage=coverage || exit 0
